### ISSUE TITLE
Random from file

### ISSUE THREAD

**Issue by chezsick** [lynxlynx/tfnoisegen#1]
Hello the lynx i like to you add from First argument to open a full file for seed the random

Thanks to add, Sick

**Comment by strlcat** [comment]
Hello,
I am sorry, but I cannot understand your issue. Please rephrase it more detailed, preferably with specifying what part of code you're talking about. It also would be cool to provide your code samples where you want to integrate tfnoisegen code into. Then reopen it.

**Comment by chezsick** [comment]
back lynx
I would like to be able to open a file from the first argument to generate a fixed random number

exemple :::::
tfrand myfile.txt
output same sequence if the same contents

**Comment by strlcat** [comment]
done in 488716e.

**Comment by chezsick** [comment]
Thanks you!
